### ISSUE TITLE
Notebook runs in the root directory instead of the current directory

### ISSUE THREAD

**Issue by Yefee** [microsoft/vscode-jupyter-hub#46] opened 2024-02-14 02:56 UTC
Thanks for the wonderful tool!

I ssh to the remote server and run the notebook in the current directory (xx/xx/SST-bias) on jupyterhub. The notebook sees the root directory instead of the current directory. See the screenshot below.

![CleanShot 2024-02-13 at 21 49 32@2x](https://github.com/microsoft/vscode-jupyter-hub/assets/6420873/61094d3c-f244-40b5-b439-0749848339b7)

**Comment by basnijholt** [comment] 2024-03-18 18:58
This is causing a lot of issues for us unfortunately, @DonJayamanne do you have any idea why this would happen?

**Comment by DonJayamanne** [comment] 2024-03-18 20:13
Sorry you are running into this issue.
Please can you fill in the issue template, we need that information to help you.

**Comment by DonJayamanne** [comment] 2024-03-19 00:53
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter-hub/issues/49

**Closed by DonJayamanne** 2024-03-19 00:53 UTC
Labels: bug, info-needed
