### ISSUE TITLE
Popup is always displayed on startup

### ISSUE THREAD

**Issue by mtreca** [microsoft/vscode-jupyter-hub#43] opened 2023-12-14 09:12 UTC
I notice that the JupyterHub extension is trying to connect to remote severs whenever I open VSCodium, even though there is no Jupyter notebook currently opened. Would it be possible to disable, or at least an option to disable, auto-connect on extension startup to reduce noise?

## Environment data

-   VS Codium version: 1.85.0.23343.16
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1002861100
-   JupyterHub Extension version (available under the Extensions sidebar): v2023.10.1003012305
-   OS (Windows | Mac | Linux distro) and version: MacOS Sonoma

**Comment by DonJayamanne** [comment] 2023-12-14 09:19
Please could you enable logging as follows:
* Open settings & go into `Jupyterhub ->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyterhub ‘ output panel.
* 
also please share a screenshot

**Comment by DonJayamanne** [comment] 2023-12-14 09:21
> even though there is no Jupyter notebook currently opened. 

that’s very weird, 
I’m assuming you have a python file opened

**Comment by mtreca** [comment] 2023-12-15 09:25
Thanks for the quick reply!

No files are opened at all, the popup appears on VSCodium startup even before selecting a project.

Here are the logs:
```
10:20:42.972 [debug] 
10:20:43.419 [debug] 
10:20:46.542 [error] Error sending request to REDACTED-URL Canceled: Canceled
    > at f.value (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64013:14)
10:20:46.543 [debug] 
10:20:46.543 [error] Error sending request to REDACTED-URL Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.543 [error] Failed to get user info for user Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.544 [debug] 
10:20:46.544 [error] Error sending request to REDACTED-URL Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.545 [debug] Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.546 [error] Error sending request to REDACTED-URL Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.547 [error] Failed to generate token, trying old way Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.547 [error] Error sending request to REDACTED-URL Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.547 [error] Failed to generate token, trying old way Canceled: Canceled
    > at raceCancellationError (/Users/maximet/.vscode-oss/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64005:11)
10:20:46.549 [debug] 
```

<img width="472" alt="Screenshot 2023-12-14 at 14 31 28" src="https://github.com/microsoft/vscode-jupyter-hub/assets/16440823/2d515c89-b9d6-4d1b-83ee-ab08ec6b0e88">

**Comment by mtreca** [comment] 2024-01-30 14:36
Thanks also for replying to this. So this is a two part problem:

- I restarted after disabling all non-JupyterHub extensions. There is no popup on startup anymore. This was indeed due to my own extension triggering on startup.
- However, opening any python file (no Jupyter notebook) will still trigger the Jupyterhub popup. These are the only enabled extensions:

<img width="425" alt="Screenshot 2024-01-30 at 15 36 14" src="https://github.com/microsoft/vscode-jupyter-hub/assets/16440823/f0805d25-f969-40f2-b238-08e70320301f">

**Comment by DonJayamanne** [comment] 2024-07-30 06:36
Duplicate of https://github.com/microsoft/vscode-jupyter-hub/issues/47

**Closed by DonJayamanne** 2024-07-30 06:36 UTC
Labels: bug, info-needed
