### ISSUE TITLE
Wrong DNS resolution

### ISSUE THREAD

**Issue by michalkahle** [microsoft/vscode-jupyter-hub#56] opened 2024-05-17 17:06 UTC
## Environment data

-   VS Code version: 1.89.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.4
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Connect to JupyterHub running at 172.17.63.10.

## Actual behaviour

Tries to connect to a wrong IP (172.16.99.211). Times out.
`Error sending request to https://horus.ikem.cz/hub/api FetchError: request to https://horus.ikem.cz/hub/api failed, reason: connect ETIMEDOUT 172.16.99.211:443`

## Attempts to diagnose/fix the problem:

1. I've tested in the browser that `https://horus.ikem.cz/hub/api` returns json `{"version": "1.5.1"}`
2. I've tried to flush DNS cache with `sudo resolvectl flush-caches`
3. I've tried to add the correct IP address to `/etc/hosts`
4. I've tested connection from node: 
```
node -e 'fetch("https://horus.ikem.cz/hub/api").then(resp => { console.log(resp.status, resp.statusText); })'
200 OK
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
18:40:59.930 [error] Error sending request to https://horus.ikem.cz/hub/api FetchError: request to https://horus.ikem.cz/hub/api failed, reason: connect ETIMEDOUT 172.16.99.211:443
    > at ClientRequest.<anonymous> (/home/mkah/.vscode-server/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:63581:18)
    > type = system
    > errno = ETIMEDOUT
    > code = ETIMEDOUT
18:43:11.001 [error] Error sending request to https://horus.ikem.cz/hub/api FetchError: request to https://horus.ikem.cz/hub/api failed, reason: connect ETIMEDOUT 172.16.99.211:443
    > at ClientRequest.<anonymous> (/home/mkah/.vscode-server/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:63581:18)
    > type = system
    > errno = ETIMEDOUT
    > code = ETIMEDOUT
18:43:11.002 [error] Failed to determine base url for https://horus.ikem.cz Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (/home/mkah/.vscode-server/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64314:9)

```

</p>
</details>

**Comment by DonJayamanne** [comment] 2024-07-30 06:44
Sorry for not getting back to you on this, please can you try the following
* Uninstall JupyterHub extension
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* Enable logging (debug logging)
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again
* Capture all the logs from the `JupyterHub` output panel
* Share the logs



[ms-toolsai-jupyter-hub-insiders.vsix.zip](https://github.com/user-attachments/files/16423209/ms-toolsai-jupyter-hub-insiders.vsix.zip)


Screenshot for enabling logging


![Image](https://github.com/user-attachments/assets/f6515fff-304f-4eff-bc88-139f9f2ce4b2)


To get to the logs, please open the bottom output panel (use the command `Outupt: Focus Output View`)
& then select `JupyterHub`


![Image](https://github.com/user-attachments/assets/309a13d9-14ea-4e70-b617-4385556e1064)

**Comment by michalkahle** [comment] 2024-08-05 08:41
Hi @DonJayamanne, thanks for support! I've loaded the vsix (v2024.5.100) and indeed was able to connect to our JupyterHub server. However, the `Jupyter` extension seems broken now:
```
Visual Studio Code (1.92.0, undefined, desktop)
Jupyter Extension Version: 2024.7.0.
Python Extension Version: 2024.12.1.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder /, Home = /home/mkah
10:25:17.980 [warn] No interpreter with path ~/miniconda3/envs/py3.10/bin/python found in Python API, will convert Uri path to string as Id ~/miniconda3/envs/py3.10/bin/python
10:28:46.383 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher' for view = 'jupyter-notebook'
10:28:46.386 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
10:30:19.241 [info] Starting Kernel (py3.11m) for 'Untitled-1.ipynb' (disableUI=false)
10:30:19.444 [info] https://horus.ikem.cz/user/~/: Kernel started: ea327278-a088-4211-9f5a-6372ebd3066a
10:30:20.830 [info] Started session for kernel startUsingRemoteKernelSpec:19a3488393a47caa2aee7e727482d7329de6e52a2b5a825773555b207f1f4112..py3.11m./home/~/mf3/envs/py3.11m/python./.-m#ipykernel_launcher
10:30:20.957 [info] Kernel successfully started
10:30:21.015 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.016 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.017 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.018 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.026 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.028 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.028 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.029 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
```

**Comment by michalkahle** [comment] 2024-08-05 08:51
I have tried to switch to release version of `JupyterHub` extension (v2023.10.1003012305) and both connection and communicating with the kernel seem to work. I used the remembered connection to JupyterHub.

**Comment by DonJayamanne** [comment] 2024-08-05 11:29
> Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
10:30:21.017 [error] Exception w

Duplicate of #64

**Closed by DonJayamanne** 2024-08-05 11:29 UTC
Labels: bug, info-needed

**Comment by DonJayamanne** [comment] 2024-08-05 13:00
> I have tried to switch to release version of JupyterHub extension (v2023.10.1003012305) and both connection and communicating with the kernel seem to work. I used the remembered connection to JupyterHub.

Sorry you are running into this issue, 
We've identified an issue with execution of cells against Jupyter Hub.
