### ISSUE TITLE
Jupyter Hub connection failure

### ISSUE THREAD

**Issue by thiagoacarvalho** [microsoft/vscode-jupyter-hub#68] opened 2024-09-04 18:46 UTC
Type: <b>Bug</b>

After the upgrade to version v2024.5.1002432242, people from my institution could no longer connect to the remote JupterHub via url with token generated in the Hub

Extension version: 2023.10.1003012305
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.40GB (1.07GB free)|
|Process Argv|--crash-reporter-id d3d9fd43-6fe2-4be3-bfdf-6b426ab2fde4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by DonJayamanne** [comment] 2024-09-04 23:47
I'm sorry you are running into this issue, and thank you for filing this issue.
Please can you confirm that reverting the extension to the older version works?
You've mentioned two versions hence the question.

Also is the token part of the Url, 
Or do you first enter the Jupyter Hub Url, then the user name and then the token?
& What quick pick are you using to connect to Jupyter Hub
Please can you share some screenshots of each step (feel free to scrub off the Url), 
    * but I'd like to quick pick options you use, and the indvidual items selected and entered, e.g. entering Url and token separately or not, etc

**Comment by vojtavozda** [comment] 2024-09-05 17:20
Hi, I can confirm I have difficulties when connecting to JupyterHub Server after update. Token is not part of the url (url: https://max-jhub.desy.de/user/, then username, then token). I tried generating new tokens, reinstalling everything and then I found out that installing the previous version (`v2023.10.1003012305`) solves the issue. Jupyter: Show Output gave me the following lines, then it stops saying `Connecting to Python 3 (ipykernel)...` in the interactive window.

```
18:32:37.211 [info] Starting Kernel () for '/Interactive-1.interactive' (disableUI=false)
18:32:37.303 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
18:32:37.378 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
18:32:37.378 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
18:32:37.676 [info] Started session for kernel connectToLiveRemoteKernel:<some uuid>
18:32:37.682 [info] Kernel successfully started
18:32:37.721 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer (repeated 30x)
```

**Comment by torbensky** [comment] 2024-09-05 23:13
I just ran into the exact same issue today. Notebooks that were previously working weren't working. I could not execute a cell. When observing the logs, I also noticed the `[error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer` error.

After a lot of troubleshooting and failing, I found that reverting the extension to version `v2023.10.1003012305` solved the problem.

**Comment by zeckem19** [comment] 2024-09-08 04:59
similar issue i see this output. i am using http://my-jupyterhub-domain.com but it seems to be fetching kernels from localhost?
``` 
12:53:59.933 [info] http://my-jupyterhub-domain.com/user/user/: Kernel started: 5e422845-47ec-4163-82b1-0579e638d4e9
12:54:00.324 [info] Started session for kernel startUsingRemoteKernelSpec:bb0b41e85d54c0b73ade4045261c0c9eeb168a535000d4b1c37ae3cdcadf8899..python3./python./.-m#ipykernel_launcher
12:54:00.944 [info] Kernel successfully started
12:54:00.952 [error] Error fetching kernels from http://localhost:8080/user/user/ (JupyterHub): FetchError: request to http://localhost:8080/user/user/api/kernels?1725771240946 failed, reason: 
    at ClientRequest.<anonymous> (/Users/~/.vscode/extensions/ms-toolsai.jupyter-hub-2024.5.1002432242/dist/extension.node.js:64208:18)
    at ClientRequest.emit (node:events:519:28)
    at Socket.socketErrorListener (node:_http_client:500:9)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by inverts** [comment] 2024-09-09 18:44
We are also encountering this issue.
I have tried both entering in the URL with the token in the query params, as well as using the username + token prompts, and creating new tokens for good measure - no luck with anything except reverting to the old version.
I did notice that in our JupyterHub server, **the kernels do get created** and I can see log messages in VSCode like this:

```
10:00:49.205 [info] Starting Kernel (my-kernel-name) for 'Untitled-1.ipynb' (disableUI=false)
10:00:50.229 [info] https://OUR.DOMAIN.URL/user/~/: Kernel started: c9ce5b90-7047-409c-b774-99f952aed3c7
10:00:58.251 [info] Started session for kernel startUsingRemoteKernelSpec:3ad1433f2b9495db89607e6b2adb8bca76cadd9432a5805eedb4d7b6b7366367..my-kernel-name./path/to/python./.-m#ipykernel_launcher
10:00:58.419 [info] Kernel successfully started
```

From the errors it seems like the maybe the user name isn't getting inserted correctly? It seems like I might expect the url in the error below to instead be something like `https://OUR.DOMAIN.URL/user/USER.NAME/`

```
09:59:17.094 [warn] Password for https://OUR.DOMAIN.URL/user/~/ was invalid.
09:59:17.523 [error] Error fetching kernels from https://OUR.DOMAIN.URL/user/~ (OUR.DOMAIN.URL): r [Error]: Forbidden
    at Function.create (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.Rl [as listRunning] (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-darwin-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
    at n.getRunningKernels (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-darwin-x64/dist/extension.node.js:181:18228)
    at async Promise.all (index 0)
    at LD.listKernelsFromConnection (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-darwin-x64/dist/extension.node.js:282:19672)
    at /Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-darwin-x64/dist/extension.node.js:282:17925 {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://OUR.DOMAIN.URL/user/~/api/kernels?1725901157097',
      status: 403,
      statusText: 'Forbidden',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
```

I hope this helps, this is a very helpful extension!

**Comment by DonJayamanne** [comment] 2024-10-07 01:25
@inverts @zeckem19 
**Please could you**
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Next, please enable `debug` logging in Jupyter Hub (open user settings and change as bellow)
![Screenshot 2024-10-07 at 12 11 21](https://github.com/user-attachments/assets/d0bd3091-c399-422c-b54c-aa5b80202f6a)
* Next, reload VS Code
* Try to replicate the issue once again
* Share the logs from the `JupyterHub` output panel.

[ms-toolsai-jupyter-hub-insiders.vsix (1).zip](https://github.com/user-attachments/files/17271603/ms-toolsai-jupyter-hub-insiders.vsix.1.zip)

**Comment by DonJayamanne** [comment] 2024-11-08 09:25
Closing this issue as it’s been almost a month since the info was requested
Please feel free to comment here and I’ll reopen this issue, or feel free to create a new one

**Closed by DonJayamanne** 2024-11-08 09:25 UTC
Labels: bug, info-needed
