### ISSUE TITLE
Filebrowser

### ISSUE THREAD

**Issue by snami100** [microsoft/vscode-jupyter-hub#37] opened 2023-10-12 07:31 UTC
In Pycharm when you add the JupyterHub Server you can also see all the files,
![grafik](https://github.com/microsoft/vscode-jupyter-hub/assets/49515753/44f19f02-8629-4020-918e-85488b28a1b2)

But in VSC you only can use the kernel. It would be better if we had something like an filebrowser, to actually open the .py files and start coding on them, so that we can run them by the Jupyter kernel, as in Pycharm.

**Comment by DonJayamanne** [comment] 2023-10-13 03:34
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1366

@snami100 Please could you upvote the above issue.

**Closed by DonJayamanne** 2023-10-13 03:34 UTC
Labels: feature-request
